version: "3.7"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./.docker/api.dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - './api/Camel:/app/Camel'
    environment:
      - APP_PATH=/app

  camel:
    container_name: gateway
    build: 
      context: .
      dockerfile: ./.docker/CAMEL.Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
        - VERSION=${VERSION}
    ports:
      - "8888:80"
    restart: always
    volumes:
      - './admin:/var/www/CAMEL/admin'
      - './auth:/var/www/CAMEL/auth'
      - './camel.conf:/var/www/CAMEL/camel.conf:ro'
      - './public:/var/www/CAMEL/public'

  db:
    container_name: camel-database
    build:
      context: .
      dockerfile: ./.docker/DB.Dockerfile
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CAMEL
      MYSQL_USER: camel
      MYSQL_PASSWORD: abcdef
