version: "3.7"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./.docker/api.dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - './api:/app'
      - './camel.conf:/app/camel.conf:ro'
      - './.htpasswd:/app/.htpasswd:ro'
      - './gunicorn_config.py:/app/gunicorn_config.py'

  camel:
    container_name: gateway
    build: 
      context: .
      dockerfile: ./.docker/CAMEL.Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - VCS_REF=${VCS_REF}
        - VERSION=${VERSION}
    ports:
      - "8888:80"
    restart: always
    volumes:
      - './admin:/var/www/CAMEL/admin'
      - './auth:/var/www/CAMEL/auth'
      - './camel.conf:/var/www/CAMEL/camel.conf:ro'
      - './public:/var/www/CAMEL/public'
      - './CAMEL.sql:/tmp/CAMEL.sql'

  db:
    container_name: camel-database
    build:
      context: .
      dockerfile: ./.docker/DB.Dockerfile
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CAMEL
      MYSQL_USER: camel
      MYSQL_PASSWORD: abcdef
